### ISSUE TITLE
How did you connect the extruder fan?

### ISSUE THREAD

**Issue by fponticelli** [halofx/Marlin-2.0-Predator#1]
Hi, I am trying to use your firmware for my predator. Similar config except that I am using TMC2130 SPI. That might have been a mistake since I don't seem to make them work - if you have any suggestion here it would be really appreciated.
On another note, how did you connect the 3-wire extruder fan to the board?

Thank you!

**Comment by halofx** [comment]
I don't have any experience with the 2130 drivers, or using SPI mode. However, you might take a look at this config. https://github.com/MarcelMo/Anycubic-3D-SKR-V1.3-TMC2130-config

I would also highly recommend checking out these Youtube channels, which have dove into the 2130 drivers.
Chris Riley : https://www.youtube.com/channel/UCqRiv7rQuxge63bqJ2hVNUQ
Edward Braiman : https://www.youtube.com/channel/UCQgi4B8mn_HYUkIImt30B9g
Teaching Tech : https://www.youtube.com/channel/UCbgBDBrwsikmtoLqtpc59Bw

As for the fan, all my fans are 2 wires at the control board. The 2 part cooling fans are wired together, and use the fan header on pin 2.3. The hot end fan for the extruder uses the HE1 header on pin 2.4, and is set here https://github.com/halofx/Marlin-2.0-Predator/commit/1673c5929b723fd99dd5f9508b84ccbd3d83241d

**Comment by fponticelli** [comment]
I ended up buying 4 TMC2209 to match your configuration :) The motors now move ... I'll open different issues for things that I am finding ... I'd be happy to contribute what I find in a markdown file if that is desired.
